Setting up the project
Am4rel/nodejs-homework-amarel pull request #2
Opened 2021-08-22 21:00 UTC by Am4rel

Подготовил код ветки, проверьте, пожалуйста.

2021-08-22 22:04 UTC, Danil44 requested changes

2021-08-22 22:04 UTC, Danil44 commented on model/index.js
> +      const contactToDelete = contacts.filter(contact => contact.id === parseInt(contactId));
.find

2021-08-22 22:04 UTC, Danil44 commented on model/index.js
> +    const contactsToRewrite = contacts.filter(contact => contact.id !== parseInt(contactId));
Навіщо це? Ти можеш оновити об'єкт через map який поверне тобі новий масив з оновленим об'єктом, тобі не потрібно видаляти контакт з масиву

2021-08-22 22:04 UTC, Danil44 commented on routes/controlls/addContact.js
> +        if (validation.error){
Перечитай логіку функції. Ти спочатку додаєш контакт, потім ти перевіряєш validation.error, хоча контакт вже доданий з невалідними даними

2021-08-22 22:04 UTC, Danil44 commented on routes/controlls/updateContact.js
> +        if (errorMessage.toString().includes("pattern")){
Навіщо дана умова і операції зі строкою всередині?

2021-08-22 22:04 UTC, Danil44 commented on utils/getId.js
> +    contacts.map(contact => ids.push(contact.id));
map не для того щоб мутувати, ще й використовуючи push всередині. map повертає новий масив.

2021-08-23 07:35 UTC, Am4rel commented on model/index.js
> +    const contactsToRewrite = contacts.filter(contact => contact.id !== parseInt(contactId));
updatedContact нужен, чтобы его можно было вернуть в ответе API.
С filter переделаю, спасибо.

2021-08-23 07:48 UTC, Am4rel commented on routes/controlls/updateContact.js
> +        if (errorMessage.toString().includes("pattern")){
Изначальная идея была в зависимости от ошибки, которую выдаёт валидатор, показывать пользователю в ответе API точную причину неудачи: там либо не все параметры могут быть указаны, либо какой-то из параметров может быть указан не верно.

Сейчас вижу, что Joi достаточно точно указывает на причину в error.message, исправлю, спасибо.

2021-08-23 07:49 UTC, Am4rel commented on utils/getId.js
> +    contacts.map(contact => ids.push(contact.id));
Заменю на forEach, спасибо.

2021-08-23 21:28 UTC, Danil44 commented on utils/getId.js
> +    contacts.map(contact => ids.push(contact.id));
навіщо? ти можеш зробити це у .map при цьому не мутуючи орігінальний масив

2021-08-23 21:30 UTC, Danil44 requested changes

2021-08-23 21:30 UTC, Danil44 commented on utils/getId.js
> +    const ids = [];
замість [] запиши в цю змінну map де ти дістаєш id

2021-08-24 22:05 UTC, Danil44 approved these changes

2021-08-24 22:05 UTC, merged